# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://syui.github.io
title: MBA-HACK2
subtitle: A blogging framework for hackers.
author: syui
description:

# Default date format is "ordinal" (resulting in "July 22nd 2007")
# You can customize the format as defined in
# http://www.ruby-doc.org/core-1.9.2/Time.html#method-i-strftime
# Additionally, %o will give you the ordinal representation of the day
date_format: "%Y/%m/%d"

# RSS / Email (optional) subscription links (change if using something like Feedburner)
subscribe_rss: /atom.xml
subscribe_email:
# RSS feeds can list your email address if you like
email:

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# If publishing to a subdirectory as in http://site.com/project set 'root: /project'
root: /
permalink: /blog/:year/:month/:day/:title/
source: source
destination: public
plugins: plugins
code_dir: downloads/code
category_dir: blog/categories
tag_dir: blog/tags
markdown: rdiscount
rdiscount:
  extensions:
    - autolink
    - footnotes
    - smart
      #- generate_toc
      #toc_token: "!TOC"
      #pygments: false # default python pygments have been replaced by pygments.rb
highlighter: pygments

paginate: 20         # Posts per page on the blog index
pagination_dir: blog  # Directory base for pagination URLs eg. /blog/page/2/
#paginate_path: "blog/page/:num/"
recent_posts: 10      # Posts in the sidebar Recent Posts section
excerpt_link: ""  # "Continue reading" link text at the bottom of excerpted articles

#excerpt_separator: "<!--more-->"
titlecase: false      # Converts page and post titles to titlecase

# list each of the sidebar modules you want to include, in the order you want them to appear.
# To add custom asides, create files in /source/_includes/custom/asides/ and add them to the list like 'custom/asides/custom_aside_name.html'
default_asides: [ asides/recent_posts.html, custom/asides/analytics_popular_posts.html, custom/asides/qiita.html, asides/delicious.html, asides/pinboard.html, asides/googleplus.html, custom/asides/hatena.html, asides/github.html, custom/asides/category_list.html, custom/asides/tag_cloud.html, custom/asides/about.html ]

# Each layout uses the default asides, but they can have their own asides instead. Simply uncomment the lines below
# and add an array with the asides you want to use.
# blog_index_asides:
# post_asides:
# page_asides:

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

# Github repositories
github_user: syui
github_repo_count: 10
github_show_profile_link: true
github_skip_forks: true

# Twitter
twitter_user: psp_t
twitter_tweet_button: false

# Google +1
google_plus_one: false
google_plus_one_size: medium

# Google Plus Profile
# Hidden: No visible button, just add author information to search results
googleplus_user:
googleplus_hidden: false

# Pinboard
pinboard_user:
pinboard_count: 3

# Delicious
delicious_user:
delicious_count: 3

# Disqus Comments
disqus_short_name: mbahack2
disqus_show_comment_count: true

# Google Analytics
google_analytics_tracking_id:

# Facebook Like
facebook_like: false

# Share Button @syui
share_button_syui: true

share_button_hatena: true
share_button_twitter: true
share_button_gplus: true
share_button_rss: true

popular_posts: 10

#lunr_search: true
#simple_search: #http://google.com/search
#simple_search: http://google.com/search
  #lunr_search: true

lunr_search: false
simple_search: http://google.com/search

